#!/usr/bin/ruby
# Stream all the files given on the commandline to the Icecast server on
# localhost. 

# originally started from example 'shoutit.rb' from ruby-shout gem

$: << File.join( File.dirname( File.readlink(__FILE__) ), './lib' )
require 'rubygems'
require 'shout'
require 'yaml'
require 'id3lib'

BLOCKSIZE = 16384

c = YAML.load_file(File.join(File.dirname(File.readlink(__FILE__)),'config.yml'))
s = Shout.new
s.host     = c[:host]   || "localhost" # beef.gina.alaska.edu
s.port     = c[:port]   || "8000"      # 8008
s.mount    = c[:mount]  || "/shoutr"   #
s.user     = c[:user]   || "source"    # 
s.password = c[:password] || "hackme"  # 
s.description = c[:description] || "" 
s.public   = c[:public] || false
s.url      = c[:url]    || "http://github.com/dayne/shoutr"
s.genre    = c[:genre]  || ""
s.name     = c[:name]   || ""


s.connect

def send_io(s,p,filename)
  puts "sending data from #{filename}"
  m = ShoutMetadata.new
  m.add 'filename', File.basename(filename)
  s.metadata = m

  while data = p.read(BLOCKSIZE)
    s.send data
    s.sync
  end
end

ARGV.each do |filename|
  target = filename if File.exists?(filename)
  next unless target
  if File.extname(target).downcase == '.mp3'
    puts "got an mp3 file, trying new code"
    tag = ID3Lib::Tag.new(target)
    cmd = "mpg123 -q -w - \"#{target}\" " + 
          " | oggenc -a \"#{tag.artist}\" -t \"#{tag.title}\" " +
          " -c \"#{target}\" -Q -"
    IO.popen(cmd,'r') { |p| send_io(s,p,filename) } 
  elsif File.extname(target).downcase == '.ogg'
    puts "got an ogg file, using old code" 
	  File.open(filename) { |f| send_io(s,f,filename) }
  end
end

s.disconnect
